### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by sharma355** [uri-t/cordouan#1]
Thanks for developing such nice tool. I faced some issues while using RUN on GUI, it shows message undefined function optimisation for input arguments of type char.

**Comment by uri-t** [comment]
Thanks! A couple questions to get better idea of what's going on:
1. What version of MATLAB are you using (or are you running the standalone app)?
2. Does the error message include a line number?

**Comment by sharma355** [comment]
Thanks for prompt response.
1. I am using 2021a version of matlab. I am on cordoun matlab app.
2. It does not include line number

**Comment by sharma355** [comment]
Thanks, it started working somehow after restart of matlab.

**Comment by uri-t** [comment]
Great! I'll close the issue. Let me know if you have any other issues!
